/**
 * Guard for the committed import-template static assets (plan tasks 6+7).
 *
 * front-cards/public/templates/import-template-{horizontal,vertical}.xlsx are
 * generated by api-server/batch-parsing/generate_import_templates.py from the
 * canonical vCard field snapshot. These tests parse the committed files through
 * the Demo pipeline and assert the headers match the snapshot exactly (order +
 * values) and that both orientations yield the same example contact — so a
 * stale or hand-edited template fails loudly here. The Python side re-verifies
 * the generator output against the same snapshot in test_batch_parsing.py.
 */
import { readFileSync } from 'fs';
import path from 'path';
import { mapRowToContactFields, parseDemoSpreadsheetFile } from './demoSpreadsheetParser';

const XLSX_MIME =
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';

const templatesDir = path.join(__dirname, '..', '..', 'public', 'templates');
const snapshotIds = (
  JSON.parse(
    readFileSync(path.join(__dirname, 'fixtures/vcard-fields.snapshot.json'), 'utf-8')
  ) as Array<{ id: string }>
).map((entry) => entry.id);

function loadTemplate(name: string): File {
  const buffer = readFileSync(path.join(templatesDir, name));
  return new File([new Uint8Array(buffer)], name, { type: XLSX_MIME });
}

describe('committed import-template workbooks', () => {
  it('horizontal template headers match the canonical snapshot exactly', async () => {
    const table = await parseDemoSpreadsheetFile(
      loadTemplate('import-template-horizontal.xlsx')
    );
    expect(table.headers).toEqual(snapshotIds);
    expect(table.rows).toHaveLength(1);
    expect(table.rows[0]).toHaveLength(snapshotIds.length);
  });

  it('vertical template parses (transposed) to the same table as the horizontal twin', async () => {
    const horizontal = await parseDemoSpreadsheetFile(
      loadTemplate('import-template-horizontal.xlsx')
    );
    const vertical = await parseDemoSpreadsheetFile(
      loadTemplate('import-template-vertical.xlsx')
    );
    expect(vertical.headers).toEqual(snapshotIds);
    expect(vertical).toEqual(horizontal);
  });

  it('example contact maps to usable vCard fields', async () => {
    const table = await parseDemoSpreadsheetFile(
      loadTemplate('import-template-horizontal.xlsx')
    );
    const fields = mapRowToContactFields(table.headers, table.rows[0]);
    expect(fields.fullName).toBe('Example Person');
    expect(fields.email).toBe('example.person@example.com');
    expect(fields.workPhone).toBe('+506 2222 0000');
    expect(fields.businessName).toBe('Example Company S.A.');
  });
});
